### ISSUE TITLE
__metadata__ property is enumerable

### ISSUE THREAD

**Issue by vit3k** [aurelia/metadata#39]
I'm not sure if this is a bug in aurelia and if it's a bug at all but `__metadata__` property is defined on object as enumerable so it's visible when enumerating over object and as a result in my case it gets stringified to json. Shouldn't it be hidden?

**Comment by EisenbergEffect** [comment]
Can you show us the code that you are writing which is producing an object with that key on it? I believe most of our code only adds that to constructors, which shouldn't result in its presence in any stringified output.

**Comment by vit3k** [comment]
I use metadata directly in my app to set some metadata on object. Example
```
let tenant = {
  firstName: '',
  lastName: ''
}
metadata.define('info', { info: 'some metadata'}, tenant)
```

and then `__metadata__` property appears on this object but it's enumerable so when I try:
```
JSON.stringify(tenant);
```
it gets serialized.
```
{"firstName":"","lastName":"","__metadata__":{"undefined":{"info":{"info":"some metadata"}}}}
```

**Comment by EisenbergEffect** [comment]
Ok. Right. The metadata api really isn't meant for general purpose usage. It's a low level implementation detail and it's primarily intended not for attaching data to objects but for attaching data to class definitions.

We could fix this, but it's pretty low priority for us since it doesn't affect almost all scenarios. If you submit a pull request that would help to address it. The PR should create a non-enumerable property if the metadata target is not a function, otherwise I think it can just set the prop as it does today, for performance reasons.

**Comment by vit3k** [comment]
Thanks for reply. I understand. Just for your information - you use it in validation framework (aurelia-validatejs) in `on` method when you use it on model instance. 

When I have time I will try to address this as it looks Reflect polyfill needs to be changed.

**Comment by EisenbergEffect** [comment]
I didn't realize it had been used there :) We definitely need to fix this.
I'm switching it to a bug, if you can submit a PR to the polyfills library, that would help. Thanks!
