### ISSUE TITLE
Origin detection

### ISSUE THREAD

**Issue by jods4** [aurelia/metadata#51]
I am spinning off the discussion with @niieani that started in [this comment](https://github.com/aurelia/pal/issues/21#issuecomment-277512506) because it deserves a thread of its own.

### Context
Aurelia uses some conventions based on module names. For example if a ViewModel doesn't explicitly indicate a view, Aurelia will assume the view is found inside a sibling module with extension `.html`.

This relies on the knowledge of which module a ViewModel came from. For everything loaded by `aurelia-loader`, this is easy because the loader tags the classes with the request they originated from.

If the ViewModel was statically imported (i.e. not through `aurelia-loader`), then things get far more tricky. This situation is unusual but possible, e.g. `aurelia-dialog` supports that. 

### Current Strategy
When asked for the origin of a ViewModel that wasn't tagged, `aurelia-metadata` currently does this:
1. Every loaded module is iterated;
2. Each exported value is compared to the ViewModel;
3. If they match the module id is attached to the ViewModel.

### Problems
The strategy is not very efficient, but that's a rare, one-time thing, so that's probably OK.
More problematic are the assumptions of steps 1. and 3.
- It is not a given that we may enumerate all loaded modules and/or get their id. 
In fact, according to @niieani we don't support that for `SystemJS`, NodeJS doesn't support it either and AFAIK it won't be possible with native ES `import`.
- Even when we can, that strategy is fragile. If a class is re-exported in another module then our logic breaks (this is not totally uncommon with the barrel "reexport everything" JS pattern).
- The new trend is scope hoisting. Rollup does it and Webpack is looking into adding support. The idea is that static dependencies can all be merged in a single scope and totally forget about modules anyway. This can result in smaller bundles, that load faster.

### Solutions?
Given the above I'm really not sure what's the way forward.

As far as webpack is concerned:
- Preserving the module id of the ViewModel would be sufficient to make it work, because webpack supports 1 and 3 (at least for now). As noted, this won't be true for all platforms.
- We could enhance code at build time to add calls to `Origin.set()`. A non-webpack build would need its own automatic (or manual) solution.

In both cases, determining when this is necessary is up for discussion.

@EisenbergEffect Thoughts?

**Comment by niieani** [comment]
I think for now, to solve Webpack we could make a simple 'origin-loader', which imports `aurelia-metadata` and calls `Origin.set()` with the proper paths in each file. I have actually thought about this in the past but decided against it (but perhaps it makes sense after all).

SystemJS wasn't a problem thus far since it cannot do split points yet, while for RJS the current logic is sufficient (albeit not great).

Going forward though, we should really think this through, since the current solution has many problems.

**Comment by niieani** [comment]
Thinking about it more, the temporary solution could probably add these `Origin.set` calls only to JS files which have a matching `.html` file (to be potentially loaded by convention). As far as I know its the only place that they're used in where we can expect exports not to be loaded via the Aurelia Loader is when we expect the convention. Unless the user makes a custom convention (for which we could document this, as the loader could take a function as an option), things should work properly.

**Comment by EisenbergEffect** [comment]
You guys seem to be a bit less familiar with what RequireJS and SystemJS can do. Both support today and have for years the ability to do "code splitting". They just don't use that terminology. That's a more Webpack term. In both cases, module iteration is supported. Additionally, the WHATWG Loader standard also specifies a registry, so this same approach works with the standard. The only real problem is the barrel pattern (outside of any challenges with Webpack).

That said, this is not something that happens the majority of the time. This code path basically only gets run when using the `compose` element against an object instance or "type" (in the case of the dialog module).

**Comment by jods4** [comment]
@EisenbergEffect 
For years and to this day I use RequireJS. 
I would point out that AFAIK RequiresJS (or AMD for that matter) does not officially have a registry. 
Our support is based on `requirejs.s.contexts._.defined` that is an implementation detail. In particular this would not work with alternative AMD loaders like Almond.

The same is true for Webpack. It works, but I don't think we should take `__webpack_require__.c` for stable and granted (this is unclear as I think there was some docs but webpack documentation is not the best. I can't find any mention of `__webpack_require__` in the 2.x docs).

I have no experience with SystemJS. Looked at it briefy 1.5 years ago but seemed not mature enough.

We want to run server-side on node. Will it work on top of the native module system (commonjs)? I don't see a registry in the documentation but I might have missed it. Of course we can run packaged apps that use another loader, like we do in the browser.

The WHATWG Loader "standard" is (I quote) _"A Collection of Interesting Ideas"_, that is undergoing large discussions/changes. They _seem_ to want a proper Registry, though. Given [their roadmap](https://github.com/whatwg/loader/blob/master/roadmap.md) it'll be years before we see this in browsers. On the flip side, as packaging is even _after_ the registry, there's probably no chance we see that format used in browsers before even later (or does HTTP/2 change that...?).

I am not sure why code splitting was brought up as it's not related to the issue. The problem is what happens when you load a class without going through `aurelia-loader` and then feed it to Aurelia.

Barrel is not the only real problem. Scope hoisting (à la Rollup) also is.

@niieani 
I think that what I'm going to do is preserve the name of modules that are linked by a convention. Turns out I already have a specific plugin for conventions, shouldn't be too hard. That will side-step the issue... for now.
It's imperfect and could be broken if you try hard enough.

**Comment by EisenbergEffect** [comment]
There are semi-supported ways to do this with the module loader libraries. I've been using them since 2010 without breaking changes. I've also talked to both James Burke an Guy Bedford about this and participated in the discussions with the WHATWG Loader group on multiple occasions over the last few years. These are known use cases and I fully expect it to be supported by the standard.

We can't remove this functionality without making breaking changes. So, we need to do the best we can to support it with each of the technologies. If a certain tech choice limits the use of technique, then we can call that out. There are relatively low-friction ways around it. I believe that there's some work on the standards to be able to get the file info for a module, so in the future, that could be encoded automatically by a compiler step.

For the time being, just do the best you can and let's have some notes on various limitations and alternative approaches.

**Comment by jods4** [comment]
@niieani You will find that the v2.0 plugins now preserve the name of modules that are source of a convention dependency (typically the link between a VM and its View), regardless of whether they are loaded statically or through `aurelia-loader`.

This should fix your issues with `aurelia-dialog`.

As we don't want to do more than that for now, I'm closing this issue.

**Comment by niieani** [comment]
I think we should keep this open, perhaps tagged as "aurelia-2.0" or something, just so we remember about this issue when thinking about breaking changes for Aurelia 2.0.

Preserving the name of modules still won't fix the issues we're having as the loader-webpack still needs to implement the logic for `PAL.eachModule` that traverses the full Webpack module cache for Origin of un-annotated modules.

**Comment by jods4** [comment]
@EisenbergEffect Feel free to reopen if you want. Is there a master list somewhere of topics to consider when doing a 2.0? That might be easier to manage than issues dispatched across repos. Besides, having lots of open issues is not a good public indicator.

> Preserving the name of modules still won't fix the issues we're having as the loader-webpack and loader-nodejs still need to correct the implementation of the logic for PAL.eachModule that traverses the full Webpack module cache for Origin of un-annotated modules.

I am not sure what the problem is? Now that the name is preserved, the loader will find the parent module of the class, with an appropriate name, and everything is well?

Do you mean that the `PAL.eachModule` implementation itself is broken? In that case shouldn't we open new issues in the appropriate repos and try to fix that?

I think getting `aurelia-dialog` to work well with the new webpack build is very important before going public with this.

**Comment by EisenbergEffect** [comment]
No list. I can create a tag for it and we can start tagging items like that. How does "vNext" sound? or should it just be "2.0"?

**Comment by jods4** [comment]
IMHO probably `2.0` rather than `vnext`, because I am sure we'll have many releases before and that could be confusing or create false expectations. Note that even the appearance of a `2.0` tag is sure to create some speculations. `long-term` might be more neutral.

**Comment by EisenbergEffect** [comment]
I like long-term. Any objections?

**Comment by niieani** [comment]
`long-term` is fine with me, although `v2.0` might be good for the hype-factor. `long-term` might come off to some as "vapor / never".

I'll take a look at the dialog issue and see if the loaders need any corrections.

**Comment by EisenbergEffect** [comment]
Closing this out since vNext doesn't do any messing with loaders, strings, module enumertion, etc. I don't think we'll be making changes to this prior to the vNext work.
