### ISSUE TITLE
Cannot find name 'SVGElementTagNameMap'

### ISSUE THREAD

**Issue by fracz** [aurelia/metadata#58]
**I'm submitting a bug report**

* **Library Version:**
1.0.3

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.12.0

* **NPM Version:**
3.10.10

* **JSPM OR Webpack AND Version**
JSPM 0.16.38

* **Language:**
TypeScript 2.6.2

**Current behavior:**
Our CI and local builds suddenly started to fail with the following error:

```
Error: typings/modules/aurelia-metadata/index.d.ts(342,33): 
error TS2304: Cannot find name 'SVGElementTagNameMap'.
```

Currently we don't have any clue what might be causing this. Any ideas?

**Comment by bigopon** [comment]
It's because of this line https://github.com/aurelia/pal/blob/master/dist/aurelia-pal.d.ts#L339
and this line https://github.com/aurelia/pal/blob/master/dist/aurelia-pal.d.ts#L348

The latest typings update in master of aurelia - pal. Thought it was a harmless update .... I didn't know SVGElementTagNameMap did not exist in typescript@2.6.2 .... oops, sorry 😄 

PR'd to fix this https://github.com/aurelia/pal/pull/36

**Comment by EisenbergEffect** [comment]
Closing as fixed.
